fix: dont auto prepend guildxyz to links in secret rewards
guildxyz/guild.xyz pull request #1091
Opened 2024-02-28 09:15 UTC by FBalint

2024-02-28 12:06 UTC, TomiOhl reviewed
Can confirm this does the job for me 👍🏻 
(I'll leave the actual approval to a frontend colleague though)

2024-03-01 21:49 UTC, BrickheadJohnny reviewed
The logic itself looks good, I wonder if we could use react-hook-form to handle the link editor input state? That way we could also use the `FormErrorMessage` component for the error message & we could also just write a validation rule + we wouldn't need to store this value in state

2024-03-05 17:11 UTC, BrickheadJohnny requested changes
Left 2 more small comments ;)

2024-03-05 17:11 UTC, BrickheadJohnny commented on src/components/lexical/plugins/ToolbarPlugin/components/LinkEditor.tsx
> +            <form
You could use `methods.handleSubmit` on the button instead (the callback which you pass to this function will receive the form state as a param), in that case you wouldn't need to use `useWatch` ;)

2024-03-05 17:11 UTC, BrickheadJohnny commented on src/components/lexical/plugins/ToolbarPlugin/components/LinkEditor.tsx
> +  const checkLinkValid = (linkToCheck: string) => {
Since this function don't have any dependencies, just a simple param, you could move it outside of the component

2024-03-06 16:14 UTC, BrickheadJohnny approved these changes

2024-03-06 17:36 UTC, merged