refactor: extend ControlledNumberInput instead of separate Conversion…
guildxyz/guild.xyz pull request #1198
Opened 2024-05-06 10:17 UTC by FBalint

…NumberInput

2024-05-07 08:09 UTC, BrickheadJohnny requested changes
Great work, but I left a couple of suggestions. Let me know if you have any questions! 👍

2024-05-07 08:09 UTC, BrickheadJohnny commented on src/requirements/WalletActivity/components/ControlledNumberInput.tsx
> +  const decimalsLimit = decimalsMax < MAX_DECIMALS ? decimalsMax : MAX_DECIMALS
nit: `Math.min(decimalsMax, MAX_DECIMALS)` might be a cleaner solution, wdyt?

2024-05-07 08:09 UTC, BrickheadJohnny commented on src/requirements/WalletActivity/components/ControlledNumberInput.tsx
> +  const updateStepSize = useCallback(
I think we could just use a `useMemo` here, so we wouldn't need a `useState`, a function wrapped in `useCallback` & a `useEffect` just to handle the `stepSize`

2024-05-07 12:56 UTC, FBalint commented
> Great work, but I left a couple of suggestions. Let me know if you have any questions! 👍

Thanks, the subform was a great idea! It also helped me realise that the whole `ConversionInput` component could be made way more generic, as you can see in newer commits.

Also, not completely related to this PR, but whilst working on this, I noticed a pattern for finding certain guildPlatforms. I extracted this logic to a simple hook called `useGuildPlatform`, and used it where I found appropriate.

2024-05-08 08:26 UTC, BrickheadJohnny approved these changes
Left 1 more short comment, otherwise LGTM!

2024-05-08 08:26 UTC, BrickheadJohnny commented on src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTokenPanel/components/TokenAmountStep.tsx
> +          <DynamicAmount tokenData={tokenData} />
I'd just call `useTokenData` inside this component ;)

2024-05-08 14:01 UTC, merged