add explorer
guildxyz/guild.xyz pull request #1555
Opened 2024-11-21 03:16 UTC by dominik-stumpf

- **chore: add explorer scaffolding**
- **feat: add infinite scroll**

2024-11-21 09:09 UTC, BrickheadJohnny requested changes
Love these changes, I left a couple of comments & I'd also bring back the sticky header as I said you today morning 😉

2024-11-21 09:09 UTC, BrickheadJohnny commented on src/app/explorer/components/InfiniteScrollGuilds.tsx
> +                <Skeleton className="size-full h-[114px]" />
Let's use the detailed guild card skeleton which I sent to you, it looks better in my opinion 😉

2024-11-21 12:44 UTC, dominik-stumpf commented on guild.d.ts
> +declare global {
I'm not certain how types will be. I would just keep them here until we generate them from the backend. This way we wont have deal with the import renamings later.

2024-11-21 15:42 UTC, BrickheadJohnny commented on src/app/explorer/components/InfiniteScrollGuilds.tsx
> +      <Button
I think we can remove this now that the infinite scroll works?

2024-11-22 00:20 UTC, dominik-stumpf commented on src/app/explorer/constants.ts
> +export const ACTIVE_SECTION = {
Do we want these kind of consts to be in screaming snake case?

2024-11-22 09:27 UTC, merged